[package]
name = "model"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "model"
path = "src/mod.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }

[dependencies.sea-orm]
version = "1.1.0"
