[package]
name = "realtime_text_editor"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3"
tokio = { version = "*", features = ["full"] }
serde = { version = "*", features = ["derive"] }
serde_json = "1.0"
futures = "0.3"
